accounts/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

djangoProject1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('blog/', include('mainapp.urls'), name='blog'),
    path('admin/', admin.site.urls),
]

mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.index, name='index'),   # zostaje wyświetlone w ../blog co jest napisane we views.py pod def index
    path('posts', views.post_list, name='post_list'),
    path('posts/<int:post_id>', views.post_detail, name='post_detail'),
]

accounts/models.py
from django.db import models

# Create your models here.

mainapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class Post(models.Model):
    STATUS_CHOICES = (
        ('prywatny', 'Prywatny'),
        ('publiczny', 'Publiczny'),
    )
    title = models.CharField(max_length=100)
    # slug = models.SlugField(max_length=250,
    #                       unique_for_date='publish', default=title)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='publiczny')

    def get_absolute_url(self):
        return reverse('mainapp:post_detail',
                       args=[self.id])

    class Meta:
        ordering = ('-publish',)  # nowe posty wyświetlają się jako pierwsze

    def __str__(self):
        return self.title


class Comment(models.Model):
    STATUS_CHOICES = (
        ('prywatny', 'Prywatny'),
        ('publiczny', 'Publiczny'),
    )

    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='publiczny')

    class Meta:
        ordering = ('publish',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)


class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='imagies')
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)

    def __str__(self):
        return self.image

# Create your models here.

mainapp/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body', 'image', 'status', 'password']
        labels = {
            'title': 'Post Title',
            'body': 'Text of your post',
            'image': 'Image:',
            'status': 'Status',
            'password': 'Access password',
        }


class PostAccess(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['password']
        labels = {
            'password': 'Access password'
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'body']
        labels = {
            'name': 'Username',
            'body': 'Text of your comment',
        }

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'mainapp/signup.html'

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.template import loader

from .models import Post, Comment
# Create your views here.


def index(request):   # tu zamiescić co chcemy zeby zostalo wyswietlone po uruchomieniu .../blog
    # return HttpResponse("To jest blog!!!.")
    return render(request, 'mainapp/base.html')


def post_list(request):
    posts = Post.objects.all()
    context = {'posts': posts}
    return render(request, 'mainapp/home.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    images = post.imagies.all()
    comments = post.comments.all()
    return render(request, 'mainapp/post_detail.html', {'post': post, 'comments': comments, 'images': images})

mainapp/templates/mainapp/base.html
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Blog</title>

    <!-- STYLESHEETS -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'mainapp/base.css' %}">
    <link rel="stylesheet" href="{% static 'mainapp/home.css' %}">

</head>

<body>
    <main class = "container">
        <!-- TEXT BANNER AT TOP OF THE SITE -->
        <header class="banner">
            <h1>
                <a class="home_link" href="{% url 'mainapp:index'  %}">
                    <img src="{% static "images/img_1.png" %}" alt="BLOG" /> </a>

            </h1>
        </header>

        <!-- NAVIGATION BAR -->
        <nav class="navigation">
            <div>
                <a class="nav_links" href="{% url 'mainapp:post_list'  %}">HOME</a>   <!-- przekierowanie na listu postow np blog/posts -->
            </div>
            <div>
                <a class="nav_links" href="base.html">LOGOWANIE</a>   <!-- przekierowanie na dodanie postu np blog/add_post -->
            </div>
            <div>
                <a class="nav_links" href="base.html">DODANIE POSTU</a>    <!-- przekierowanie na logowaie np blog/log_in-->
            </div>
        </nav>

        <!-- MAIN CONTAINER WITH 3 SHORTS OF ARTICLES -->
        <section class="articles">

            {% block content %}
                Welcome to out blog. Nice to see you there!
            {% endblock %}


            <!-- //kod do posta
                <article class="single_article">
                    <h2 class="articles_headers">Post title</h2>
                    <p>Lorem ipsum, sample text of the article.</p>
                </article>

                <section class="comments">
                    <h3 class="articles_headers">Comments</h3>
                    <div class="single_comment">
                        <h4 class="nicknames">Guest Nickname</h4>
                        <p>
                            Hello, nice post.
                        </p>
                    </div>

                    <div class="single_comment">
                        <h4 class="nicknames">Guest Nickname</h4>
                        <p>
                            Very good!
                        </p>
                    </div>

                </section>

            -->
        </section>

        <!-- FOOTER - THE END OF THE SITE WIT AUTHORS, SOCIALS, COPYRIGHT ETC. -->
        <footer class="footer">
            <p> 2021 &copy All rights are reserved!</p>
        </footer>
    </main>

</body>
</html>

mainapp/templates/mainapp/email_template.html
Hello,
HERE IS YOUR POST :)


{{ post.title }}

{{ post.body }}

Created by {{ post.author }}, release in {{ post.publish }}

Thank you for reading our website!

mainapp/templates/mainapp/error.html
{% extends 'mainapp/base.html' %}

{% block content %}
   <div class="title">
        <h3 class="header_new_post"> Your password is incorrect! </h3>
   </div>
{% endblock %}

mainapp/templates/mainapp/home.html
{% extends 'mainapp/base.html' %}

{%  block content %}
        <!-- MAIN CONTAINER WITH 3 SHORTS OF ARTICLES -->
        <section class="articles">
            <h2 class="section_label">POSTS</h2>

            {%  for post in posts %}
                <h3>
                    <a href="{% url 'mainapp:post_detail' post.id %}">{{ post.title }}</a>
                </h3>
            {% endfor %}
         <!--   <article class="short_article">
                <h3 class="articles_headers">
                    <a class = "" href = "{{ post.get_absolute_url }}">
                        {{ post.title }}
                    </a>
                </h3>

                <p>
                    Published {{ post.publish }} by {{ post.author }}
                </p>

                <p>
                    {{ post.body|truncatewords:30|linebreaks }}
                </p>
            </article> -->
<!--
            <article class="short_article">
                <h3 class="articles_headers">Post title</h3>
                <p>Lorem ipsum, sample text of the article.</p>
            </article>

            <article class="short_article">
                <h3 class="articles_headers">Post title</h3>
                <p>Lorem ipsum, sample text of the article.</p>
            </article>


-->
        </section>
{%  endblock %}

mainapp/templates/mainapp/my_posts.html
{% extends 'mainapp/base.html' %}

{%  block content %}
        <!-- MAIN CONTAINER WITH 3 SHORTS OF ARTICLES -->
        <section class="articles">
            <h2 class="section_label">MY POSTS</h2>

            {%  for post in posts %}
                {% if post.author is user %}
                    <article class="short_article">

                    <h3 class="articles_headers">
                        <a href="{% url 'mainapp:post_detail' post.id %}">{{ post.title }}</a>
                    </h3>

                    <p>
                         {{ post.status }}
                    </p>

                    <p>
                        Published {{ post.publish }} by {{ post.author }}
                    </p>

                    <p>
                        {{ post.body|truncatewords:30|linebreaks }}
                    </p>

                    </article>
                {% endif %}
            {% endfor %}

        </section>
    {% include "mainapp/pagination.html" with page=posts %}
{%  endblock %}

mainapp/templates/mainapp/new_comment.html
{% extends 'mainapp/base.html' %}

{% block title %}
    <h2> Adding a comment </h2>
{% endblock %}

{% block content %}
            {% if comment %}
                <h3>Your comment has been added.</h3>
            {% else %}
                <h3> New comment </h3>
                <form method="post" class="post-form">{% csrf_token %}
                        {{ form.as_p }}
                    <button type="submit" class="save btn btn-default">Save</button>
                </form>
            {% endif %}
{% endblock %}

mainapp/templates/mainapp/pagination.html
<div class="pagination">
 <span class="step-links">
  {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
  {% endif %}
    <span class="current">
  Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
  {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
  {% endif %}
  </span>
</div>

mainapp/templates/mainapp/pdf_render.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta charset="UTF-8">
        <title>PDF render post</title>

        <style type="text/css">

              body
              {
                  font-family: "Times New Roman";
                  font-size: 12px;
              }

              .articles_headers
              {
                  text-align: center;
                  font-family: 'Georgia';
                  font-size: 24px;
                  color: #9BBCE4;
              }

              .subtext
              {
                  color: #555555;
                  text-align: center;
              }

        </style>
    </head>

    <body>
        <main class = "container">
            <section class="articles">

                {% block content %}

                    <article class="single_article">

                        <h2 class="articles_headers">
                           <b> {{ post.title }} </b>
                        </h2>

                        <em class="subtext">
                            Published {{ post.publish }} by {{ post.author }}
                        </em>

                        <hr />

                        <p>
                            {{ post.body|linebreaks }}
                        </p>

                    </article>

                {% endblock %}

            </section>
        </main>
    </body>
</html>

mainapp/templates/mainapp/post_access.html
{% extends 'mainapp/base.html' %}

<head>
     {% load static %}
    <link rel="stylesheet" href="{% static 'mainapp/post_new.css' %}">
</head>

{% block content %}
   <div class="title">
        <h2> You haven't the permission to see the post! </h2>
   </div>
    <h4> Write the password to get the access to post </h4>
    <form method="post" class="post-form" >
                {{ form.as_p }}
                 {% csrf_token %}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

mainapp/templates/mainapp/post_detail.html
{% extends 'mainapp/base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}

    <article class="single_article">

        <h2 class="articles_headers">
            {{ post.title }}
        </h2>

        <p>
            Published {{ post.publish }} by {{ post.author }}
        </p>

        <p>
            {{ post.body|linebreaks }}
        </p>

    </article>

    <section class="images">

     <!--  <h3 class="articles_headers">Comments </h3> -->

         {%  for image in images %}

            <div class="single_image">

                <p>
                    {{ image.image }}
                </p>
            </div>
         {% empty %}
  		    <p>
                There are no images yet.
            </p>
         {% endfor %}
    </section>

    <section class="comments">

        <h4 class="articles_headers">Comments</h4>

         {% for comment in comments %}

            <div class="single_comment">

                <p>
                    Comment {{ forloop.counter }}
                    by  <h5 class="nicknames">{{ comment.name }} </h5>
      		         {{ comment.publish }}
                </p>

                <p>
                    {{ comment.body|linebreaks }}
                </p>
            </div>

         {% empty %}
  		    <p>
                There are no comments yet.
            </p>
         {% endfor %}
    </section>

{% endblock %}

mainapp/templates/mainapp/post_new.html
{% extends 'mainapp/base.html' %}

<head>
     {% load static %}
    <link rel="stylesheet" href="{% static 'mainapp/post_new.css' %}">
</head>

{% block title %}
    <h2> Adding a post </h2>
{% endblock %}

{% block content %}
   <div class="title">
        <h3 class="header_new_post"> New post </h3>
   </div>
    <form method="post" enctype="multipart/form-data" class="post-form">{% csrf_token %}
                {{ form.media }}
                {{ form.as_p }}
        <h5>*Enter the password, if status = Private</h5>
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

mainapp/templates/mainapp/searching.html
{% extends 'mainapp/base.html' %}

{% block content %}

    <section>
            <form method=POST action="{% url 'mainapp:searching' %}">
                {% csrf_token %}
               <label> Searching a post: <input type="search" placeholder="Search a post..." name = "searched" ></label>
                <button type="submit">Search</button>
            </form>
    </section>

    {% if searched %}
        <p> Searching <b>{{ searched }}</b> </p>
        {% for post in posts %}

            <article class="short_article">

                <h3 class="articles_headers">
                    <a href="{% url 'mainapp:post_detail' post.id %}">{{ post.title }}</a>
                </h3>

                  <!--   <p>
                         {{ post.status }}
                     </p> -->

                     <p>
                        Published {{ post.publish }} by {{ post.author }}
                    </p>

                    <p>
                        {{ post.body|truncatewords:30|linebreaks }}
                    </p>

                </article>

        {%  endfor %}

    {% else %}
        <p> Error! You wrote wrong phrase. </p>
    {% endif %}

{% endblock %}

mainapp/templates/mainapp/signup.html
{% extends 'mainapp/base.html' %} &nbsp;

{% block content %}
<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign up</button>
</form>
{% endblock content %}